# Generated by Django 4.2.1 on 2023-05-04 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
